//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Byakhee.rc
//
#define IDC_OPENEXISTING                3
#define IDD_ABOUTBOX                    100
#define IDS_CAPTION_OPTIONSSHEET        102
#define IDS_CAPTION_OPTIONSDLG          102
#define IDS_CAPTION_NEWINVESTIGATOR     103
#define IDC_FIELDEDIT                   120
#define IDC_FIELDEDITLISTBOX            121
#define IDS_CAPTION_NEWWEAPONDLG        122
#define IDD_PROPSHEET_NEWWEAPON_PAGE1   123
#define IDD_PROPSHEET_NEWWEAPON_PAGE2   124
#define ID_VIEW_INFORMATION             127
#define IDR_MAINFRAME                   128
#define IDR_SHEETTYPE                   129
#define IDR_SCRIPTEDITTYPE              130
#define IDR_HANDOUTTYPE                 131
#define IDD_WIZARD_NEWINVESTIGATOR_PAGE1 131
#define IDR_SCRIPTEDITTYPE_SHEET        132
#define IDD_WIZARD_NEWINVESTIGATOR_PAGE2 132
#define IDR_SCRIPTEDITTYPE_RULEFILE     133
#define IDD_WIZARD_NEWINVESTIGATOR_PAGE3 133
#define IDR_SCRIPTEDITTYPE_HANDOUT      134
#define IDD_WIZARD_NEWINVESTIGATOR_PAGE4 134
#define IDD_WIZARD_NEWINVESTIGATOR_PAGE5 135
#define IDD_WIZARD_NEWINVESTIGATOR_PAGE6 136
#define IDD_WIZARD_NEWINVESTIGATOR_PAGE7 137
#define IDB_LIGHTBULB                   139
#define IDD_PROPSHEET_OPTIONS_PAGE1     140
#define IDD_PROPSHEET_OPTIONS_PAGE2     141
#define IDD_PROPSHEET_OPTIONS_PAGE3     142
#define IDD_PROPSHEET_OPTIONS_PAGE4     143
#define IDD_PROPSHEET_OPTIONS_PAGE5     144
#define IDD_PROPSHEET_OPTIONS_PAGE6     145
#define IDB_WIZARD_NEWINVESTIGATOR      146
#define IDI_RANDOM                      147
#define IDI_PENANDPAPER                 148
#define IDD_TIP                         149
#define IDD_CHARACTERAGE                150
#define IDD_OPTIONALSKILLS              151
#define IDD_CHOOSESKILL                 152
#define IDI_UNDO                        153
#define CG_IDS_TIPOFTHEDAY              154
#define IDS_TIPOFTHEDAY                 154
#define CG_IDS_TIPOFTHEDAYMENU          155
#define IDS_TIPOFTHEDAYMENU             155
#define CG_IDS_DIDYOUKNOW               156
#define IDS_TIPOFTHEDAYHELP             156
#define IDI_INFO                        157
#define IDB_DIALOG_NEWDOCUMENT          158
#define IDD_NEWDOCUMENT                 159
#define IDI_INVESTIGATOR_WIZARD         160
#define CG_IDS_FILE_ABSENT              161
#define CG_IDP_FILE_CORRUPT             162
#define CG_IDS_TIPOFTHEDAYHELP          163
#define IDI_SCRIPT                      166
#define IDI_NEWSCRIPT                   166
#define IDC_HAND                        169
#define IDD_ADDSKILL                    171
#define IDR_BASESTRINGPOPUP             172
#define IDD_EDITSKILLS                  173
#define IDR_WEAPONBASESTRINGPOPUP       173
#define IDD_EDITSKILL                   174
#define IDD_EDITWEAPONS                 175
#define IDD_SPELLBOOK                   177
#define IDI_CLOSEDBOOK                  178
#define IDI_OPENBOOK                    179
#define IDI_PAGE                        180
#define IDB_SPLASH                      181
#define IDI_NEWSHEETSCRIPT              181
#define IDI_RUNSCRIPT                   182
#define IDD_EDITVALUE                   183
#define IDI_NEWRULEFILE                 183
#define IDI_NEWHANDOUTSCRIPT            184
#define IDB_TOOLBAR_NEWDOCDLG           186
#define IDC_DRAGDROP                    190
#define IDC_DRAGSWAP                    191
#define IDD_QUICKINFO                   191
#define IDB_TIPOFTHEDAY                 192
#define IDC_BULB                        1000
#define IDC_STARTUP                     1001
#define IDC_NEXTTIP                     1002
#define IDC_TIPSTRING                   1004
#define IDC_SAVEVERSION                 1009
#define IDC_SAVEVERSIONDESC             1010
#define IDC_USERTEXTFONT                1011
#define IDC_TOPMARGIN                   1012
#define IDC_BOTTOMMARGIN                1013
#define IDC_LEFTMARGIN                  1014
#define IDC_RIGHTMARGIN                 1015
#define IDC_TOPMARGINSPIN               1016
#define IDC_KNOW                        1017
#define IDC_LUCK                        1018
#define IDC_IDEA                        1019
#define IDC_BOTTOMMARGINSPIN            1020
#define IDC_SAN                         1020
#define IDC_LEFTMARGINSPIN              1021
#define IDC_HP                          1021
#define IDC_RIGHTMARGINSPIN             1022
#define IDC_DB                          1022
#define IDC_SKILLPOINTS                 1031
#define IDC_INTERESTPOINTS              1032
#define IDC_AGE                         1033
#define IDC_AGESPIN                     1034
#define IDC_REROLL                      1035
#define IDC_CANEDIT                     1036
#define IDC_EXTRASCHOOLING              1038
#define IDC_STR                         1040
#define IDC_CON                         1041
#define IDC_DEX                         1042
#define IDC_OCCUPATION                  1042
#define IDC_APP                         1043
#define IDC_USECHARACTERISTICMODIFIERS  1043
#define IDC_SIZ                         1044
#define IDC_INT                         1045
#define IDC_EDU                         1046
#define IDC_POW                         1047
#define IDC_ALLWEAPONS                  1047
#define IDC_INVESTIGATORWEAPONS         1048
#define IDC_ADD                         1049
#define IDC_REMOVE                      1050
#define IDC_SKILLLIST                   1054
#define IDC_NAME                        1055
#define IDC_RANDOMNAME                  1056
#define IDC_SEX                         1058
#define IDC_BIRTHPLACE                  1059
#define IDC_MENTALDISORDERS             1060
#define IDC_BROWSE                      1062
#define IDC_PORTRAIT                    1063
#define IDC_CHARACTERISTIC1             1064
#define IDC_CHARACTERISTIC2             1065
#define IDC_CHARACTERISTIC3             1066
#define IDC_NUMBEROFOPTIONS             1066
#define IDC_CHARACTERISTIC4             1067
#define IDC_SKILLS                      1067
#define IDC_CUSTOMPROMPT                1070
#define IDC_UNDO                        1071
#define IDC_COLLEGESDEGREES             1072
#define IDC_INFORMATION                 1074
#define IDC_AVAILABLETYPES              1076
#define IDC_NEWDOCUMENT_TYPES           1077
#define IDC_TOOLBAR                     1080
#define IDC_CHOOSESKILLS                1081
#define IDC_SKILLNAME                   1087
#define IDC_BASE                        1088
#define IDC_INSERTSPECIALTEXT           1089
#define IDC_ADVANCED                    1090
#define IDC_SKILLTYPE1                  1091
#define IDC_SKILLTYPE2                  1092
#define IDC_NUMBEROFSUBSKILLS           1093
#define IDC_NUMBEROFSUBSKILLS_SPIN      1094
#define IDC_DIVIDER                     1095
#define IDC_LISTWITHMAINSKILLS          1096
#define IDC_EDIT                        1099
#define IDC_DELETE                      1100
#define IDC_NEW                         1101
#define IDC_RANGE                       1104
#define IDC_ATTACKS                     1105
#define IDC_BULLETS                     1106
#define IDC_MAL                         1108
#define IDC_DAMAGE                      1109
#define IDC_SHOTS                       1110
#define IDC_HITPOINTS                   1111
#define IDC_SPELLLIST                   1112
#define IDC_INVESTIGATORSPELLS          1117
#define IDC_NEWVALUE                    1119
#define IDC_NEWVALUECOMBO               1120
#define IDC_FULLWIZARD                  1127
#define IDC_COMPONENTLIST               1133
#define IDC_CHANGE                      1134
#define IDC_FLATTOOLBAR                 1136
#define IDC_EMAILAUTHOR                 1138
#define IDC_MAILARTIST                  1139
#define IDC_ARTISTWEB                   1140
#define IDC_MAILTIPS                    1141
#define IDC_MAILCIMAGE                  1142
#define IDC_DELTAGREENWEB               1143
#define IDC_CHAOSIUMWEB                 1144
#define IDC_AUTHORWEB                   1145
#define IDC_DONTTELLMEAGAIN             1148
#define IDC_DLGICON                     1150
#define IDC_TEXTAREA                    1154
#define IDC_ANIMATEDFIELDEDIT           1155
#define IDC_FRAME1                      1156
#define IDC_FRAME2                      1157
#define IDC_SHOWTIPS                    1158
#define ID_VIEW_LARGEICON               28713
#define ID_VIEW_SMALLICON               28714
#define ID_VIEW_LIST                    28715
#define ID_VIEW_DETAILS                 28716
#define ID_VIEW_ACTIVATE_SHEETSTYLE     32745
#define ID_VIEW_SHEETSTYLE              32775
#define ID_TOOLS_CHECKSHEET             32777
#define ID_TOOLS_INCOME                 32778
#define ID_TOOLS_OPTIONS                32779
#define ID_FILE_EXPORT_BYAKHEE20        32788
#define ID_FILE_EXPORT_BYAKHEE10        32789
#define ID_FILE_EXPORT_HTML             32790
#define ID_VIEW_REFRESH_SHEET           32792
#define ID_EDIT_NEXTFIELD               32793
#define ID_EDIT_PREVFIELD               32794
#define ID_INVESTIGATOR_ADDSKILL        32799
#define ID_INVESTIGATOR_MODIFYSKILL     32800
#define ID_INVESTIGATOR_SETRANDOMNAME   32801
#define ID_INVESTIGATOR_REROLL          32802
#define ID_TOOLS_RANDOMNAME             32803
#define ID_TOOLS_REROLL_INVESTIGATOR    32804
#define ID_INVESTIGATOR_INCOME          32805
#define ID_INVESTIGATOR_CHOOSEWEAPONS   32806
#define ID_BASESTRINGPOPUP_APP          32807
#define ID_BASESTRINGPOPUP_CON          32808
#define ID_BASESTRINGPOPUP_DEX          32809
#define ID_BASESTRINGPOPUP_EDU          32810
#define ID_BASESTRINGPOPUP_INT          32811
#define ID_BASESTRINGPOPUP_POW          32812
#define ID_BASESTRINGPOPUP_SIZ          32813
#define ID_BASESTRINGPOPUP_STR          32814
#define ID_BASESTRINGPOPUP_LUCK         32815
#define ID_BASESTRINGPOPUP_KNOW         32816
#define ID_BASESTRINGPOPUP_IDEA         32817
#define ID_BASESTRINGPOPUP_SAN          32818
#define ID_BASESTRINGPOPUP_HP           32819
#define ID_BASESTRINGPOPUP_MAGIC        32820
#define ID_BASESTRINGPOPUP_NONE         32821
#define ID_BASESTRINGPOPUP_NOMODIFY     32822
#define ID_BASESTRINGPOPUP_COREFIREARM  32823
#define ID_VIEW_LIKECTHULHU5_5          32824
#define ID_VIEW_USERTEXT                32825
#define ID_VIEW_BLANKSHEET              32826
#define ID_BASESTRINGPOPUP_BASE_AS_SKILL 32827
#define ID_VIEW_CUSTOMSKILLSINUSERTEXT  32828
#define ID_INVESTIGATOR_SPELLBOOK       32829
#define ID_VIEW_OUTPUT                  32830
#define ID_TOOLS_ROLLCHECKEDSKILLS      32831
#define ID_TOOLS_RUNSCRIPT              32834
#define ID_VIEW_HIDEOUTPUT              32836
#define ID_VIEW_ALLSKILLPERCENTILES     32837
#define ID_TOOLS_CLIPSKILLPOINTS        32839
#define IDS_TOOLBARKEY                  61446
#define ID_VIEW_RULEFILEINFORMATION     61447
#define ID_INDICATOR_LINENUMBER         61448
#define ID_INDICATOR_POINTS             61449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           164
#endif
#endif
